import React from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const q = async (path:string, apiKey:string)=>{ const r=await fetch(API+path,{headers:{'X-API-Key':apiKey}}); if(!r.ok) throw new Error(await r.text()); return r.json(); };

function App(){
  const [run,setRun]=React.useState(''); const [service,setService]=React.useState(''); const [search,setSearch]=React.useState(''); const [apiKey,setApiKey]=React.useState('');
  const summary=useQuery({queryKey:['summary',run,apiKey],enabled:Boolean(apiKey),queryFn:()=>q('/api/v1/resources/summary'+(run?'?inventory_run_id='+encodeURIComponent(run):''),apiKey)});
  const resources=useQuery({queryKey:['resources',run,service,search,apiKey],enabled:Boolean(apiKey),queryFn:()=>q('/api/v1/resources?limit=100'+(run?'&inventory_run_id='+encodeURIComponent(run):'')+(service?'&service='+encodeURIComponent(service):'')+(search?'&search='+encodeURIComponent(search):''),apiKey)});
  const runs=useQuery({queryKey:['runs',apiKey],enabled:Boolean(apiKey),queryFn:()=>q('/api/v1/inventory-runs?limit=25',apiKey)});
  const [accessKeyId,setAccessKeyId]=React.useState(''); const [secretAccessKey,setSecretAccessKey]=React.useState(''); const [sessionToken,setSessionToken]=React.useState(''); const [startError,setStartError]=React.useState('');
  async function start(){ if(!accessKeyId||!secretAccessKey||!apiKey)return; setStartError(''); const response=await fetch(API+'/api/v1/inventory-runs',{method:'POST',headers:{'content-type':'application/json','X-API-Key':apiKey},body:JSON.stringify({credentials:{access_key_id:accessKeyId,secret_access_key:secretAccessKey,session_token:sessionToken||null}})}); if(!response.ok){setStartError('No se pudieron validar las credenciales AWS.'); return;} setAccessKeyId(''); setSecretAccessKey(''); setSessionToken(''); runs.refetch(); }
  async function download(path:string, filename:string){ const response=await fetch(API+path,{headers:{'X-API-Key':apiKey}}); if(!response.ok) throw new Error(await response.text()); const url=URL.createObjectURL(await response.blob()); const link=document.createElement('a'); link.href=url; link.download=filename; link.click(); URL.revokeObjectURL(url); }
  return <div className="app"><header><div><h1>AWS Cloud Inventory</h1><p>Read-only inventory using credentials held only for the active run</p></div><div className="actions"><input type="password" autoComplete="off" placeholder="API key (not stored)" value={apiKey} onChange={e=>setApiKey(e.target.value)}/><input autoComplete="off" placeholder="AWS access key ID" value={accessKeyId} onChange={e=>setAccessKeyId(e.target.value)}/><input type="password" autoComplete="off" placeholder="AWS secret access key" value={secretAccessKey} onChange={e=>setSecretAccessKey(e.target.value)}/><input type="password" autoComplete="off" placeholder="AWS session token (optional)" value={sessionToken} onChange={e=>setSessionToken(e.target.value)}/><button onClick={start} disabled={!apiKey||!accessKeyId||!secretAccessKey}>Run inventory</button>{startError&&<p className="error">{startError}</p>}</div></header>
  <main><section className="cards"><Card t="Resources" v={summary.data?.resource_count ?? '—'}/><Card t="Accounts" v={summary.data?.accounts?.length ?? '—'}/><Card t="Services" v={summary.data?.services?.length ?? '—'}/><Card t="No Owner" v={summary.data?.missing_owner ?? '—'}/></section>
  <section className="panel"><div className="toolbar"><select value={run} onChange={e=>setRun(e.target.value)}><option value="">All runs</option>{runs.data?.items?.map((r:any)=><option key={r.run_id} value={r.run_id}>{r.run_id.slice(0,8)} · {r.status}</option>)}</select><select value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{summary.data?.services?.map((s:string)=><option key={s}>{s}</option>)}</select><input placeholder="Search name, ID or ARN" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>download('/api/v1/resources/export.csv'+(run?'?inventory_run_id='+encodeURIComponent(run):''),'aws-inventory.csv')} disabled={!apiKey}>CSV</button><button onClick={()=>download('/api/v1/resources/export.json'+(run?'?inventory_run_id='+encodeURIComponent(run):''),'aws-inventory.json')} disabled={!apiKey}>JSON</button></div>
  <table><thead><tr><th>Name</th><th>Type</th><th>Service</th><th>Account</th><th>Region</th><th>State</th><th>Owner</th><th>Environment</th></tr></thead><tbody>{resources.data?.items?.map((r:any)=><tr key={r.resource_type+r.resource_id}><td>{r.resource_name||r.resource_id}</td><td>{r.resource_type}</td><td>{r.service}</td><td>{r.account_id}</td><td>{r.region||'global'}</td><td>{r.state||'—'}</td><td>{r.owner||<span className="warn">missing</span>}</td><td>{r.environment||'—'}</td></tr>)}</tbody></table></section>
  <section className="panel"><h2>Inventory runs</h2><table><thead><tr><th>Run</th><th>Status</th><th>Started</th><th>Resources</th><th>Errors</th></tr></thead><tbody>{runs.data?.items?.map((r:any)=><tr key={r.run_id}><td>{r.run_id}</td><td>{r.status}</td><td>{new Date(r.started_at).toLocaleString()}</td><td>{r.resource_count}</td><td>{r.error_count}</td></tr>)}</tbody></table></section></main></div>
}
function Card({t,v}:{t:string,v:any}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);
